APPLICATION_HOST_EMAIL_ADDRESS = 'log-my-workout@joewestersund.net'
APPLICATION_HOST_NAME = "Joe Westersund"
APPLICATION_EMAIL_ADDRESS = 'log-my-workout@joewestersund.net'
APPLICATION_NAME = "Log My Workout"
APPLICATION_SHORT_NAME = "LMW"
APPLICATION_NAME_FOR_LOGO = "LMW"